### ISSUE TITLE
Bitrate/Bitdepth label stopped working

### ISSUE THREAD

**Issue by v1rusnl** [Inrixia/neptune-plugins#20] opened 2024-03-02 19:06 UTC
Tidal Desktop version 2.36.2

Suddenly stopped working. 
![image](https://github.com/Inrixia/neptune-plugins/assets/18641204/c2ce6b0c-0129-4562-9a95-6af8bd73857e)

Labels are still visible though.
![image](https://github.com/Inrixia/neptune-plugins/assets/18641204/a8ab3ce8-077a-4271-b99a-623af1e4aca1)

Seems Tidal changed something again, like last time...

**Comment by v1rusnl** [comment] 2024-03-02 21:09
#18

**Comment by Inrixia** [comment] 2024-03-07 21:17
I'm gonna close this as a duplicate of #18 just so the conversation can be focused there. Please follow that issue thx <3

**Closed by Inrixia** 2024-03-07 21:17 UTC
