### ISSUE TITLE
TidalTags seems to crash albums with videos

### ISSUE THREAD

**Issue by CurtAD** [Inrixia/neptune-plugins#61] opened 2024-08-13 16:41 UTC
Hello!

Earlier, I was testing to see why albums with videos keep displaying "Sorry, this content is no longer available" message. I discovered that something in the TidalTags plugin was causing the error message.

When TidalTags is disabled, the error does not happen anymore. I was just wondering if something in the plugin was causing it, turns out it might be the case.

Is there a fix for this, or will I be better off disabling it for now if I want to listen to albums with videos in them?

Thanks!

**Comment by Inrixia** [comment] 2024-08-13 21:11
Can you link a album that this happens on?

**Comment by Inrixia** [comment] 2024-08-13 21:39
But you can still play content regardless right?

I suspect this is because the id's of those items don't exist as tracks.

**Comment by Inrixia** [comment] 2024-08-13 21:46
Weird, I'll have a look into it when I get time.

Thanks for letting me know

**Comment by RebellionBritney** [comment] 2024-08-21 03:23
I can confirm that. Content no longer available message pop up every time I try to play a video, even in the Videos section in my library

**Comment by Inrixia** [comment] 2024-08-23 05:22
Please let me know if this isnt fixed thx

**Comment by RebellionBritney** [comment] 2024-08-23 07:22
> Please let me know if this isnt fixed thx

No, still happenning. Also happens with Song Downloader, Always Exclusive and RealMAX

**Comment by Inrixia** [comment] 2024-08-23 07:26
> No, still happenning. 

Can you restart your client and try again? Testing with https://tidal.com/browse/album/223006955 works fine for me

**Comment by RebellionBritney** [comment] 2024-08-25 04:23
In my case still happens with TidalTags, RealMAX and Song Downloader... only got fixed with Always Exclusive

**Comment by Inrixia** [comment] 2024-08-25 04:25
Can you link what album/track is causing the crash.

And also go and make sure all the plugins are updated. Restarting your client is the best way to handle this.

**Comment by RebellionBritney** [comment] 2024-08-25 07:05
The crash is with all the videos:
Videos section in my library
Videos section on artist page
Albums with videos
Clicking in the three dots in any video

I'm always restarting my client and deleting cache and that kind of stuff

**Comment by Inrixia** [comment] 2024-08-25 23:22
I cant reproduce this sorry, and everyone else I have spoken to has had no issues since the fix was published so there isnt anything I can do here sorry. If anyone else is having issues please re-open and maybe we can try figure it out. 

If you want to chat more about this please hop on the discord and maybe we can figure out what's causing it.

**Closed by Inrixia** 2024-08-25 23:22 UTC
