### ISSUE TITLE
RealMAX Bug Causing Failed Playback 

### ISSUE THREAD

**Issue by bbreakthrough** [Inrixia/neptune-plugins#96] opened 2024-10-31 18:03 UTC
I have only found this issue so far on this one particular track, but when my RealMAX plugin stumbles upon these two files, the popup text repeatedly states that it has found a higher quality version and playback will seemingly queue up the higher quality track but ends up just repeating the very beginning of the song endlessly while spamming the client with the popup text.

The song is Julia Michaels' Give It To You from Songland

https://tidal.com/browse/track/140665352
https://tidal.com/browse/track/140671306

A search on the platform shows the first link as being HiRes (thanks to TidalTags) which from what I could find should be the highest quality version available on the platform and only really finds these two versions for me (excluding the presumably lower quality versions on random playlists).

Would love to know if this bug is reproducible for others or if it's just on my end. I didn't reset my cache or anything like that yet since this is literally the first and only song I've encountered the issue with. Let me know if the issue can't be reproduced and I'll try some of those steps. Also let me know if there's any sort of debug info you need me to try and find.

**Comment by bbreakthrough** [comment] 2024-11-01 00:06
So I had this happen for the second time on a different playlist. So I cleared my cache which didn't appear to help. Had to reset my app data and import my neptune plugins again, which fixed the issue with the above case as well as the new case. So there's unlikely to be any app data to be gleaned now that it is fixed. However, if this issue were to occur again, would there be any steps / debug info you'd like me to collect? Not sure if any of the standard TIDAL app logs/network logging would have been helpful for you.

**Comment by Inrixia** [comment] 2024-11-01 23:38
This sounds like a issue where invalid data somehow gets into the response cache. Though Its hard to really know without being able to replicate it. The cache persists across reinstalls etc but clearing your appdata would have cleared it.

Ill close this for now since its not reproducible, but if you or anyone else runs into it again please re-open it and let me know :)

Thanks for reporting it

**Comment by MinaPT** [comment] 2024-11-05 06:47
i played a song and real max was stuck in a loop trying to find the higher version until my tidal crashed, for some reason i cant open the console. heres a few songs it happened with, maybe someone can reproduce it and open the console.  https://tidal.com/browse/track/303777077?u https://tidal.com/browse/track/303777074?u https://tidal.com/browse/track/303777080?u

**Comment by adamvanw** [comment] 2024-11-05 16:28
I ran into this with 3 songs from one album as well.

https://tidal.com/track/286103662?u
https://tidal.com/track/286103671?u
https://tidal.com/track/286103673?u

It was my first installation of RealMAX and I was playing from my Liked Tracks prior to and after installation.
I started cherry-picking songs to test in the Liked Tracks till I clicked on $20. All of the songs affected were in my Liked Tracks, but the rest of the songs in the album were fine. I also tried adding a song from the album to my Liked Tracks, but it still worked fine.
After a few restarts, it just started working normally. I tried reproducing similar steps on my laptop, but I couldn't run into it again.
Hope some of the additional context can help!

**Comment by Inrixia** [comment] 2024-11-05 23:04
I don't think I can reproduce this, will leave it open for now. If someone can get their console output when this happens that might help.

**Closed** 2024-11-06 00:43 UTC

**Comment by Inrixia** [comment] 2024-11-06 00:44
I was able to reproduce it. Seems like Tidal might have been reporting a track as not having **HiRes** quality when it does causing RealMAX to constantly queue the "HiRes" version which was just the exact same track.

There is now a check ensuring that RealMAX wont queue the same track id that is currently playing :)

Please let me know if you encounter this bug again after restarting to apply the fix.
