### ISSUE TITLE
Cover Theme doesn't work for some users

### ISSUE THREAD

**Issue by n1ckoates** [Inrixia/neptune-plugins#66] opened 2024-08-19 01:50 UTC
Creating an issue to track information about this bug.

For some users, the request to get the album cover (with `?cors` at the end) is failing, which results in Cover Theme not working at all.

I'm not currently able to reproduce the issue, although I did previously experience it (though I didn't investigate further at the time).

**Comment by Inrixia** [comment] 2024-08-23 05:24
Closing as I cant reproduce this either. If someone runs into this please re-open

**Comment by Inrixia** [comment] 2024-08-23 14:25
Issue is due to the node-vibrant library failing to fetch image.

Migrating palette code to native and using a better library:  **https://www.npmjs.com/package/@behold/sharp-vibrant**

Should fix it.

**Closed** 2024-08-24 02:44 UTC
